backend:
  name: git-gateway
  branch: "'add-cms'" # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "site/static/images/team" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/images/team" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    
    files:
      - label: "Team Members page"
        name: "team"
        file: "content/team.json"
        widget: list
        fields:
          - label: persons
            name: team
            widget: list
            fields:
              - {label: Photo, name: photo, widget: image}
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Bio, name: bio, widget: markdown}
      - label: "Impact Page"
        name: "impact"
        file: "content/impact.json"
        widget: list
        fields:
          - label: impact
            name: content1
            widget: list
            fields:
              - {label: img, name: image, widget: image}
              - {label: heading, name: heading, widget: string}
              - {label: body, name: body, widget: markdown}
              - label: points
                name: points
                widget: list
                fields:
                  - {label: Point,name: point,widget: string}
  

            
              
 