backend:
  name: git-gateway
  branch: "'add-cms'" # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "site/static/images/team" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/images/team" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Team"
    name: "team"
    
    files:
      - label: "Team Members"
        name: "team"
        file: "content/team.json"
        widget: list
        fields:
          - label: page_title
            name: team
            widget: list
            fields:
              - {label: Photo, name: photo, widget: image}
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Bio, name: bio, widget: markdown}
              
 